### ISSUE TITLE
Throw pretty error if `config/ouija.json` not found

### ISSUE THREAD

**Issue by mattcreager** [ouija-io/ouija#20]
Gross:

```
module.js:340
    throw err;
          ^
Error: Cannot find module './config/ouija.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mcreager/repos/work/ouija-example/content/apps/ouija/gulpfile.js:10:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by halfdan** [comment]
I think this is solved already: https://github.com/goinstant/ouija/blob/master/gulpfile.js#L12-L16 (in fa8345c7a)
